# Generated by Django 3.0.6 on 2020-05-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('entidad', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=200)),
            ],
        ),
    ]
